spring:
  redis:
    host: 192.168.1.115
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1ms
  cache:
    type: redis
  session:
    redis:
      save-mode: on_set_attribute
server:
  port: 9090