spring:
  redis:
    host: 192.168.1.153
    port: 6379
    database: 0
  cache:
    type: redis
  session:
    redis:
      save-mode: on_set_attribute
    hazelcast:
      map-name: spring:session:redis:session
server:
  port: 9090